CREATE TABLE IF NOT EXISTS `#__mailtester_emails` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`subject` VARCHAR(255)  NOT NULL ,
`body` TEXT NOT NULL ,
`state` TINYINT(1)  NOT NULL ,
`senddate` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
`createddate` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
`created_by` INT(11)  NOT NULL ,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8_general_ci;

